[package]
name = "xsetwacom-fe"
version = "0.1.0"
authors = ["Samuel Batissou <samuelbatissou@gmail.com>"]

[dependencies]
text_io = "0.1.7"

[dependencies.gtk]
version = "0.4.0"
features = ["v3_16"]

